version: '0.0.{build}'
clone_folder: C:\gopath\src\github.com\guitarrapc/watchdog-symlinker

environment:
  GOPATH: C:\gopath
  matrix:
  - _GOOS: windows
    _GOARCH: amd64
  - _GOOS: linux
    _GOARCH: amd64

install:
  - set PATH=%PATH%;%GOPATH%\bin
  - set GOOS=%_GOOS%
  - set GOARCH=%_GOARCH%
  - set GO111MODULE=on

build_script:
  - go build
  - 7z a "watchdog-symlinker_%GOOS%_%GOARCH%_%APPVEYOR_BUILD_VERSION%.zip" "%APPVEYOR_BUILD_FOLDER%/watchdog-symlinker*"

artifacts:
  - path: "watchdog-symlinker_%GOOS%_%GOARCH%_%APPVEYOR_BUILD_VERSION%.zip"
    name: watchdog-symlinker_%GOOS%_%GOARCH%_%APPVEYOR_BUILD_VERSION%.zip