version: '0.0.{build}'
clone_folder: C:\gopath\src\github.com\guitarrapc/watchdog-symlinker

environment:
  GOPATH: C:\gopath
  matrix:
  - _GOOS: windows
    _GOARCH: amd64
  - _GOOS: linux
    _GOARCH: amd64

install:
  - go get -u github.com/golang/dep/cmd/dep
  - set PATH=%PATH%;%GOPATH%\bin

before_build:
  - set GOOS=%_GOOS%
  - set GOARCH=%_GOARCH%

build_script:
  - dep ensure
  - go build
  - 7z a "%APPVEYOR_BUILD_FOLDER%/watchdog-symlinker_%GOOS%_%GOARCH%_%APPVEYOR_BUILD_VERSION%.zip" "%APPVEYOR_BUILD_FOLDER%/watchdog-symlinker*"

artifacts:
  - path: "%APPVEYOR_BUILD_FOLDER%/watchdog-symlinker_%GOOS%_%GOARCH%_%APPVEYOR_BUILD_VERSION%.zip"
    name: watchdog-symlinker_%GOOS%_%GOARCH%_%APPVEYOR_BUILD_VERSION%.zip